#!/bin/bash

JAVA_VER=1.7.0_60

mkdir -p ${3}/usr/${B_LIBDIRS}/jvm/

rsync -avP openjdk.build/j2re-image/ ${3}/usr/${B_LIBDIRS}/jvm/jre-${JAVA_VER}/
rsync -avP openjdk.build/j2sdk-image/ ${3}/usr/${B_LIBDIRS}/jvm/jdk-${JAVA_VER}/

rm ${3}/usr/${B_LIBDIRS}/jvm/jre-${JAVA_VER}/lib/security/cacerts ${3}/usr/${B_LIBDIRS}/jvm/jdk-${JAVA_VER}/jre/lib/security/cacerts

ln -s /etc/ssl/certs/java/cacerts ${3}/usr/${B_LIBDIRS}/jvm/jre-${JAVA_VER}/lib/security/cacerts
ln -s /etc/ssl/certs/java/cacerts ${3}/usr/${B_LIBDIRS}/jvm/jdk-${JAVA_VER}/jre/lib/security/cacerts
